[WIP] GHA: Use download-artifact@v1 for caching SWIG build

diff --git a/.github/workflows/android.yml b/.github/workflows/android.yml
--- a/.github/workflows/android.yml
+++ b/.github/workflows/android.yml
@@ -18,28 +18,45 @@ jobs:
       with:
         java-version: 1.8
     - name: Checkout SWIG
-      if: steps.cache-swig.outputs.cache-hit != 'true'
+#      if: steps.cache-swig.outputs.cache-hit != 'true'
       uses: actions/checkout@v2
       with:
         repository: swig/swig
         path: swig
-    - name: Install SWIG from source
-      if: steps.cache-swig.outputs.cache-hit != 'true'
-      run: |
-        sudo apt-get -yqq install automake bison
-        cd swig
-        git log -1
-        ./autogen.sh
-        ./configure --prefix=$PWD/dist
-        make
-        make install
-    - name: Cache SWIG build
-      id: cache-swig
-      if: success()
-      uses: actions/cache@v1
+    - uses: actions/download-artifact@v1
+      continue-on-error: true
       with:
+        name: swig-bin
         path: swig/dist
-        key: ${{ runner.os }}-swig
+    - name: Install SWIG from source
+#      if: steps.cache-swig.outputs.cache-hit != 'true'
+#      if: failure()
+      run: |
+        if ! [ -d swig/dist]; then
+          sudo apt-get -yqq install automake bison
+          cd swig
+          git log -1
+          ./autogen.sh
+          ./configure --prefix=$PWD/dist
+          make
+          make install
+        else
+          echo swig downloaded
+          ls swig/dist
+        fi
+    - name: Upload SWIG distribution
+      uses: actions/upload-artifact@v1.0.0
+      continue-on-error: true
+      with:
+        name: swig-bin
+        path: swig/dist
+#    - name: Cache SWIG build
+#      id: cache-swig
+#      if: success()
+#      uses: actions/cache@v1
+#      with:
+#        path: swig/dist
+#        key: ${{ runner.os }}-swig
     - name: Build with Gradle & SWIG
       run: |
         export PATH=$PWD/swig/dist/bin:$PATH
